version: "1.0"
type: route
data:
  url: "/services/snapraidaio/configs/edit/:uuid"
  title: _("Edit")
  editing: true
  notificationTitle: _("Edit config.")
  component: omv-services-snapraidaio-configs-form-page
