version: "1.0"
type: component
data:
  name: omv-services-snapraidaio-settings-form-page
  type: formPage
  config:
    request:
      service: SnapRaidAio
      get:
        method: get
      post:
        method: set
    fields:
      - type: checkbox
        name: enable
        label: _("Enable")
        value: false
    buttons:
      - template: submit
      - template: cancel
        execute:
          type: url
          url: "/services/snapraidaio"
